# Generated by Django 5.1 on 2024-08-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('agency_logo', models.ImageField(blank=True, null=True, upload_to='images/agency_logo')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('subject_address', models.TextField(blank=True, null=True)),
                ('subject_photograph', models.ImageField(upload_to='images/subject_photograph')),
                ('subject_signature', models.ImageField(upload_to='images/signature')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=1000, unique=True)),
                ('project_name', models.CharField(max_length=512)),
                ('project_type', models.CharField(blank=True, max_length=512, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShotList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_description', models.TextField(blank=True, null=True)),
                ('shot_type', models.CharField(blank=True, choices=[('Extreme Close Up Shot', 'Extreme Close Up Shot'), ('Close Up Shot', 'Close Up Shot'), ('Medium Shot', 'Medium Shot'), ('Wide Shot', 'Wide Shot'), ('Extreme Wide Shot', 'Extreme Wide Shot')], max_length=512, null=True)),
                ('image_reference', models.ImageField(blank=True, null=True, upload_to='images/reference_image')),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
