# Generated by Django 5.1 on 2024-08-10 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shotlist_user_remove_project_shot_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='consent_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.consentform'),
        ),
    ]
