# Generated by Django 5.1 on 2024-08-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_project_consent_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='shot_list',
        ),
        migrations.AddField(
            model_name='project',
            name='shot_list',
            field=models.ManyToManyField(blank=True, related_name='projects', to='api.shotlist'),
        ),
    ]
