# Generated by Django 5.1 on 2024-08-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_project_shot_list_project_shot_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consentform',
            name='agency_logo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='consent_form',
        ),
    ]
