# Generated by Django 5.1 on 2024-08-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_consentform_agency_logo_project_consent_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='consent_form',
        ),
        migrations.AddField(
            model_name='project',
            name='consent_form',
            field=models.ManyToManyField(blank=True, related_name='projects', to='api.consentform'),
        ),
    ]
