# Generated by Django 5.1 on 2024-08-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_project_consent_form_project_consent_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='consent_form',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='api.consentform'),
        ),
    ]
