# Generated by Django 5.1 on 2024-08-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_project_collaborators_alter_project_consent_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='subject_photograph',
            field=models.ImageField(blank=True, null=True, upload_to='images/subject_photograph'),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='subject_signature',
            field=models.ImageField(blank=True, null=True, upload_to='images/signature'),
        ),
    ]
