# Generated by Django 5.1 on 2024-08-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_project_options_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_at']},
        ),
    ]
