# Generated by Django 5.1 on 2024-08-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_project_options_project_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consentform',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='shotlist',
            options={'ordering': ['updated_at']},
        ),
        migrations.AddField(
            model_name='consentform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='consentform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shotlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shotlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
