# Generated by Django 5.1 on 2024-08-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_consentform_options_alter_shotlist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shotlist',
            name='shot_type',
            field=models.CharField(blank=True, choices=[('extreme-close-up', 'extreme-close-up'), ('Close-Up-Shot', 'Close-Up-Shot'), ('Medium-Shot', 'Medium-Shot'), ('Wide-Shot', 'Wide-Shot'), ('Extreme-Wide-Shot', 'Extreme-Wide-Shot')], max_length=512, null=True),
        ),
    ]
