# Generated by Django 5.1 on 2024-08-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_shotlist_options_alter_shotlist_shot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shotlist',
            name='image_reference',
            field=models.URLField(blank=True, null=True),
        ),
    ]
