# Generated by Django 5.1 on 2024-08-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_shotlist_image_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shotlist',
            name='shot_type',
            field=models.CharField(blank=True, choices=[('Extreme Close Up', 'Extreme Close up'), ('close-up', 'Close Up'), ('medium-shot', 'Medium Shot'), ('wide-shot', 'Wide Shot'), ('extreme-wide-shot', 'Extreme Wide Shot')], max_length=512, null=True),
        ),
    ]
