# Generated by Django 5.1 on 2024-08-30 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_shotlist_shot_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shotlist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='shotlist',
            name='shot_type',
            field=models.CharField(blank=True, choices=[('Extreme Close Up', 'Extreme Close up'), ('Close Up', 'Close Up'), ('Medium Shot', 'Medium Shot'), ('Wide Shot', 'Wide Shot'), ('Extreme Wide Shot', 'Extreme Wide Shot')], max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='shotlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
