# Generated by Django 5.1 on 2024-08-30 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_shotlist_options_alter_shotlist_shot_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='shot_list',
            field=models.ManyToManyField(blank=True, related_name='shot_lists', to='api.shotlist'),
        ),
        migrations.AlterField(
            model_name='shotlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shot_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
